# Generated by Django 4.0 on 2021-12-16 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_alter_eventstats_click_cost_alter_eventstats_clicks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventstats',
            name='date_recorded',
            field=models.DateField(default=datetime.datetime(2021, 12, 16, 13, 17, 52, 291718)),
        ),
    ]
